### PR TITLE
Update 2020-01-14-test-markdown-post.md

### PR DESCRIPTION
**Pull request by santarabantoosoo**

### CODE REVIEW

**Review by santarabantoosoo — COMMENTED** [review]
approved

**Review by santarabantoosoo — COMMENTED** [review]
Done

**Review by jesa06 — APPROVED** [review]
Reviewed

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues and PRs_

Thank you for opening this PR, and I'm really sorry I haven't gotten around to reviewing it.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this PR with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽

**Pull request closed without merging**
