### PR TITLE
Optimized Diagram Image

### PR DESCRIPTION
**Pull request by anushbhatia**
This will enhance the overall SEO for the site if you approve this, I can make a pr for other branches too.

### CODE REVIEW

**Comment by hamelsmu** [comment]
What kind of optimization is being done here?  What does this change mean?  Can you explain a bit more about what you did?

**Comment by anushbhatia** [comment]
Okay SIr actually the original image site 73.6 kb around an i optimized it to 43 kb which intern would reduce the time take in FCP(First Content Full Paint)

**Comment by anushbhatia** [comment]
fastpages _ An easy to use blogging platform with support for Jupyter Notebooks  and 4 more pages - Personal - Microsoft​ Edge 01-08-2020 14_54_32
I wanted to enhance the Performance for this which can be brought upto 92 around

**Comment by hamelsmu** [comment]
Ok!  Thanks so much !!

**Pull request merged**
