### PR TITLE
"Introducing fastpages" Blog Post

### PR DESCRIPTION
**Pull request by hamelsmu**
in addition to this blog post, made the following minor corrections

- corrected css to include list elements
- correcting a minor spacing issue in the site header
- added instructions on removing example blog posts.
- make sure this blog post gets deleted in the setup process

**Note: once this PR is merged, it will take ~ 5 minutes for the blog to appear on https://fastpages.fast.ai/**

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 the launch blog post is ready for review.  A preview is available here:  https://5e5078158b8469a184037ad9--fastpages.netlify.com/2020/02/21/introducing-fastpages.html

(I suppose we can use the NBReview App if we have comments on the post)

**Comment by hamelsmu** [comment]
Generating a fresh preview, as I merged a bunch of PRs while this was opened and since merged those changes back into this branch.

/preview

**Comment by jph00** [comment]
Looking better @hamelsmu . Here's a suggested redraft of the initial features list:

----

- Create posts containing code, code outputs (which can be interactive), formatted text, and so forth, directly from [Jupyter Notebooks](https://jupyter.org/); for instance see [this great example post](https://drscotthawley.github.io/devblog3/2019/02/08/My-1st-NN-Part-3-Multi-Layer-and-Backprop.html) from Scott Hawley. Notebook posts support features such as:
  - Hide or show cell input and output.
  - Collapsable code cells that are either open or closed by default.
  - Define the Title, Summary and other metadata via a special markdown cells
  - Add links to [Colab](https://colab.research.google.com/) and GitHub automatically
- Create posts, including formatting and images, directly from Microsoft Word documents
- Create and edit [Markdown](https://guides.github.com/features/mastering-markdown/) posts entirely online using GitHub's built-in markdown editor
- Embed Twitter cards and YouTube videos
- ... and [much more](https://github.com/fastai/fastpages).

----

Then you can also remove the stuff about online markdown editor and the link to Scott's blog.

Suggest waiting until Monday to launch since weekends are quiet.

**Comment by hamelsmu** [comment]
Sounds good, @jph00.  Summary of changes I just made: 

- Changed the feature list per the above feedback
- Added documentation re: the new categories feature to the notebook
- removed redundant mention of Scott's blog from the end b/c now its in the feature bulleted list
- removed mention of online markdown editor b/c it is now in the bulleted feature list

/preview

**Comment by hamelsmu** [comment]
Ok image previews are supported (tested this in slack message to myself)

image

**Comment by hamelsmu** [comment]
Merging this now @jph00 will let you do the honors of announcing it whenever you are ready (will take ~ 5 min for it to show up )

**Pull request merged**
