### PR TITLE
[Ready to Merge] fixed windows fonts

### PR DESCRIPTION
**Pull request by hamelsmu**
Tested it on mac and inside a windows VM, seems reasonable to me, now. 

 I actually like the Windows rendering better than the mac but the difference is subtle

### CODE REVIEW

**Comment by hamelsmu** [comment]
ok @jph00 the preview is ready https://5e449f2a5f133e990b53ff93--fastpages.netlify.com

I ran windows inside a VM to test it out, looked good to me, but perhaps it's worth another pair of eyes on it.

**Comment by jph00** [comment]
lgtm

**Pull request merged**
