### PR TITLE
fastlinkcheck blog post

### PR DESCRIPTION
**Pull request by hamelsmu**

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 ready for review: https://5fb6201b06a7c998adf6d30f--fastpages.netlify.app/fastlinkcheck/

**Comment by jph00** [comment]
This looks great @hamelsmu. The only thing I'd suggest adding is something towards the top mentioning a couple of other popular link checkers, and stating that they're also useful, but don't have the local link checking functionality, so they require deploying or serving your site prior to running them.

**Pull request merged**
