### PR TITLE
support for auto pulling gdocs

### PR DESCRIPTION
**Pull request by nthomsencph**
The purpose of this pull request is to add support for the export of specified Google docs as `.docx` files into the `/_word` directory prior to the call to the `word2post.sh` script. This enables users to store their blog posts securely in Drive and then automatically pull them on build. Note that these documents needs to be publicly available in order for this to work. However, since the goal is to publish on a fastpage, I don't think this should raise concerns for users.

There are two additions in this request:

- The `_action_files/gdocs2word.py` script which uses the request lib to pull down documents through a download link. 

- A `gdoc_ids.json` file that holds ids of the document that one wants to include. 
Users simply need to add docs, e.g.

```
{
    "gdoc_ids": [
        "1d1N-2j56BVRVXOFPRlJRdgictahCVMGmklRtYRVGD1E"
    ]
}
```

Document titles are automatically retrieved from the request header.

### CODE REVIEW

**Review by randombrad — APPROVED** [review]

**Review by randombrad — APPROVED** [review]

**Review by Peter-Rambeck — COMMENTED** [review]
why

**Comment by Peter-Rambeck** [comment]
That's it

**Comment by nthomsencph** [comment]
> That's it

@Peter-Rambeck could you clarify? This enables users to conveniently write in Google Docs. This is in addition to .docx which is already supported.

**Comment by Peter-Rambeck** [comment]
Sorry, it's dummy comment as comments was somehow required to proceed.

**Comment by nthomsencph** [comment]
> Sorry, it's dummy comment as comments was somehow required to proceed.
> 
> 

No worries. Feedback encouraged.

**Review by Vibhu83 — APPROVED** [review]

**Review by Vibhu83 — APPROVED** [review]

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues and PRs_

Thank you for opening this PR, and I'm really sorry I haven't gotten around to reviewing it.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this PR with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽

**Pull request closed without merging**
