### PR TITLE
Add options force_date and free_structure to enable more generic use for this action.

### PR DESCRIPTION
**Pull request by A-Alaa**
Regarding #35 and #34 
But this PR only works for the notebooks now.

### CODE REVIEW

**Comment by A-Alaa** [comment]
@hamelsmu please feel just to drop the whole idea (i.e to delete the PR and the two issues)

**Comment by hamelsmu** [comment]
Ok please discuss feature requests in the fastai forums thank you

**Comment by hamelsmu** [comment]
Didn’t mean to close the PR just wanted to say let’s discuss in forums and then come back here

**Comment by MaxBalashov** [comment]
I vote for adding this feature into project like an option. Personaly I interested in free structure.
I'd like to create such blog:

1. Linear regression:
    - ...;
    - ...;
    - ...;
2. KNN:
    - ...;
    - ...;
    - ...;
3. ...

**Pull request closed without merging**
