### PR TITLE
[Do Not Merge] Fastpages Blog Post: show observable example

### PR DESCRIPTION
**Pull request by hamelsmu**
Add a fastpages blog post example to fastpages that showcases open source javascript libraries and with references to Observable notebooks 

cc: @thomasballinger @jph00 

P.S. I backdated this blog post so that it appears under the "announcing fastpages" one.

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 @thomasballinger the draft blog post is ready to review at https://5e5ef1ddb0f9aa5d04bcae2f--fastpages.netlify.com/fastpages/jupyter/2020/02/19/observable

**Comment by thomasballinger** [comment]
This indeed looks like current state of the art for embedding from the Observable side, hoping to improve this experience in the future. I like the link back to the Observable notebook, I think it makes it more clear how to use this example.

Since there's a CSS issue, I'd prefer to use a different Observable notebook. I can provide one tomorrow.

---

More on the CSS issue: Observable cells embedded this way share styles with the embedding environment (the theme here I guess?) because they're not in an iframe, so the slider thumbs are positioned wrong.

image

If we used a normal input (`<input type="range"></input>` renders fine for me) instead of this custom one this wouldn't be a problem, but this is an accurate representation of what can currently happen when using different styles like this.

I'd rather use a different example because it could be confusing to folks to see this.

**Comment by hamelsmu** [comment]
@thomasballinger no problem, I would rather have something easier to understand- I’ll leave this PR open until you come back with something else.  Thanks for your help

**Comment by thomasballinger** [comment]
Here's a notebook with embed code in it https://observablehq.com/@ballingt/embedding-example

reproduced here:
~~~js
<div id="observablehq-d310b45d"></div>
<script type="module">
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@ballingt/embedding-example.js?v=3";
const inspect = Inspector.into("#observablehq-d310b45d");
(new Runtime).module(define, name => (
  name === "vegaPetalsWidget" ||
  name === "viewof minSepalLength" ||
  name === "viewof minSepalWidth")
&& inspect());
</script>
~~~

This doesn't fix any fundamental issues, but by using the builtin range-type input it should render fine and not cause additional confusion of why the sliders look different in FastPages vs Observable.

**Comment by thomasballinger** [comment]
@hamelsmu points out to me that is we use this new notebook, it'll be confusing to keep linking to tutorial.

I think either:
1. You change the link here to point to this this new example instead of the tutorial,
2. I can change the tutorial to use the normal sliders to avoid the CSS issue, or
3. we move forward with the (only slightly) broken CSS, the current state of the code, and I'll make a pull request later to improve as our embedding API changes.

I'd rather not do 3. but I'm fine with 1 or 3, and I hope to make a PR updating the embedding API in the next month regardless.

**Comment by hamelsmu** [comment]
Ok.  I thought about this carefully, and perhaps this is not the right time to be nudging the fastai community to make Observable visualizations, as it might cause more confusion than value.  Also, I'm weary that the CSS tweaks will start to become unwieldy or collide with other things so maybe its best to find another way.  It seems like it could be worth waiting just a little bit longer for the inerface to be cleaned up and then it will perhaps it will be easier to explain.  

One concern is that we are just showing one visualization but people may want to try many more, so this thread makes me feel like a robust test of many different kinds of visualizations are necesary first ( Like a notebook with many examples w/ different kinds of widgets). 

Therefore, closing this PR for now.  But Look forward to a PR from you in the future @thomasballinger I'm excited about the possibilities of folks using open source javascript libraries for visualizations in fastpages.  

Thanks

**Comment by thomasballinger** [comment]
Thanks for your thoughtfulness here! Looking forward to making a PR here with a better embedding API in the future.

**Pull request closed without merging**
