### PR TITLE
Support user/organization sites

### PR DESCRIPTION
**Pull request by albertvillanova**
Add support for user/organization sites.

### CODE REVIEW

**Comment by albertvillanova** [comment]
For user/organization sites, it is required an additional setup step:
- After the merge of the automatic setup PR is completed, you need to go to the Settings tab and set `gh-pages` as the source branch.

**Comment by hamelsmu** [comment]
@albertvillanova have you tested this to see if it works?  I tried creating a blog from your template at https://github.com/hamelsmu/hamelsmu.github.io and I cannot get the site to build for me.  Do you want to test this on your end and troubleshoot?

**Comment by albertvillanova** [comment]
Hi @hamelsmu. Yes, I have tested it twice (see my testing details below) and it works!

I think I know what your problem is. As I previously wrote in my comment above, it is required an additional setup step for user/organization sites:
- Go to your repo Settings tab: https://github.com/hamelsmu/hamelsmu.github.io/settings
- And in the *GitHub Pages* section, choose the branch `gh-pages` as your publishing *Source* (note that for user/organization sites it will be set by default the `master` branch)
- Click Save
And that's all. Your site should be working perfectly at https://hamelsmu.github.io/

I have tested it twice:
- First, in a dummy user site I created ad hoc
- Second, in my own personal site, where I synced all project content from the dummy user repo

**Comment by hamelsmu** [comment]
> In the GitHub Pages section, choose the branch gh-pages as your publishing Source

I'm looking into how to do this automatically

**Comment by albertvillanova** [comment]
@hamelsmu if you find the way, please tell me so. I also tried to find it out without success...

**Comment by hamelsmu** [comment]
> After the merge of the automatic setup PR is completed, you need to go to the Settings tab and set gh-pages as the source branch.

Can you add instructions to do this in the README?

**Comment by hamelsmu** [comment]
waiting for https://github.com/fastai/ghapi/pull/4

**Review by hamelsmu — APPROVED** [review]

**Pull request merged**
