### PR TITLE
Simplify setup procedure

### PR DESCRIPTION
**Pull request by albertvillanova**
Use GITHUB_TOKEN instead of SSH_DEPLOY_KEY to deploy the site.

This simplifies the setup procedure as there is no longer need to create the SSH Deploy Key, nor the Repository Secret (both requested by the automatic setup Pull Request).

### CODE REVIEW

**Comment by albertvillanova** [comment]
Eventually, the `_fastpages_docs/_setup_pr_template.md` should be updated.

**Comment by hamelsmu** [comment]
The `GITHUB_TOKEN` doesn't have permissions to deploy

**Comment by hamelsmu** [comment]
Clarification - the TOKEN doesn't have permissions to deploy on the first try, user has to go into settings and enable the branch.  the SSH key on the other hand has authority to do this

**Comment by hamelsmu** [comment]
Let's reopen this and think about it more.

**Comment by albertvillanova** [comment]
I was thinking that for the user is much less work going to the Settings tab and enable the gh-pages branch, rather than all the tedious procedure to create an SSH_KEY_DEPLOY key and a Repo secret.

And if finally the PR to support the user/organization site is accepted, the user will need to go to the Settings tab and enable the gh-pages branch anyway.

But if you think it is better like is, it's OK! ;)

**Comment by hamelsmu** [comment]
Cool give it a week or so we are working on an automated solution to all of
this.  Thanks for your PR

**Comment by hamelsmu** [comment]
waiting on https://github.com/fastai/ghapi/pull/4

**Comment by hamelsmu** [comment]
At the end of the day I had to rollback the repository to its original state.  This idea did not end up working because of the following reasons:

- A GitHub Action cannot trigger another GitHub Action, so using the GITHUB_TOKEN to do the first deploy doesn't trigger a page build.  This forces the user make some kind of arbitrary change to their repository, which involves an additional step after enabling GitHub pages.   The user has to do this **EVERYTIME** there is any kind of step taken by GitHub Actions like an automated upgrade, etc.  which is confusing.
- GitHub Actions does not have the proper authorization to enable GitHub pages.  You have to create a personal access token to enable this instead which unlike the deploy key has far wider access priviliges than just a repository.  


However, it was a good try!  Sorry it didn't work out.

**Comment by albertvillanova** [comment]
@hamelsmu, I see you have forced pushed to the remote branch, changing the public repo history... I thought this was not considered a good practice... Nevermind! ;)

And yes, when I tried to automatize the enabling of GH Pages, I found out that GitHub Actions only have READ access for administrative tasks (like enabling GH Pages). That is the reason why I asked you to tell me so if you eventually find a way around: https://github.com/fastai/fastpages/pull/456#issuecomment-734357031

So let me summarize to see if I have properly understood:
- Currently:
  - the user is requested to create manually a repo Secret and also a SSH Deploy Key
  - GH Pages is enabled automatically
  - there is no support for user/organization sites
- I was proposing:
  - the user has to enable manually GH Pages
  - no need to create repo Secret nor SSH Deploy Key
  - user/organization sites are supported

And you think the first procedure is better.

**Comment by hamelsmu** [comment]
Hello @albertvillanova 

You are correct that blowing away the git history as I did is a bad idea because it garbled in history and your pull request.  Due to my own ignorance on the best way to revert a large number of commits, I didn't realize that a force push would do this and was trying to recover to an earlier state.  You are correct in pointing this out as a bad practice.  I'm truly sorry about this it was not intentional.

Furthermore, by force pushing, I gave off the impression that I didn't value your contributions.  In fact, I think your PR was really brilliant.  By reverting your changes with a force push I made it look like I prioritized my point of view over yours.  I didn't mean to do this, and I can explain myself better.  

These are the issues I encountered after merging the PR

- GitHub Pages was not building automatically open merging the setup PR.  
- Not only do you have to enable GitHub pages-  but before that you must manually create a gh-pages branch ( or add automation in to do this ).  So you have to wait until the right time to enable GitHub pages.
- Depending on the timing of when you enable GitHub pages, you may have to make another change to the repo to trigger yet another build. 

I thought this was confusing and was concerned that the experience for setting up new users would be jarring as that is the point of greatest churn in a project like this, as any flakiness after the initial setup process can turn users off.  

I will admit to one more mistake that I had made is that I should have requested you to make a repository template where your final state was in your master branch so we could test your template completely before bringing it to this repository.  That way we could have iterate on it a bit more there rather than the stressful experience of trying to fix things live and having to do an emergency rollback.  

If you are willing to take me up on the offer to iterate on a fork on this repo together, perhaps your current fork that would be wonderful.  Thanks again and sorry about all the confusion.

**Comment by albertvillanova** [comment]
Hi @hamelsmu 

First, I would like to sincerely thank you for your kind message. I would also like to thank you for fastpages: you have made an amazing work and it is a fantastic project. 

My PR just pretended to improve fastpages a little bit by giving support for user/organization pages, as I think it is really a pity they are not currently supported.

I take up your proposal: let me work a little on the fork and then let me know if it is worth it and/or how it could be improved. If it is OK for you.

My comment about forced push was just due to the fact that I wanted to try to find out what problems had arisen from the merge, but it was not possible because the merge had been erased from the history of the repo. Just that. I understand you: we sometimes make some non "best practices" when we are stressed having to fix a problem in production as fast as possible. For reverting the merge of a pull request, GitHub gives an easy to use option: just above in this conversation, on the right of your merge commit
```
 hamelsmu merged commit fb0f767 into fastai:master yesterday
```
you have a **Revert** button. You can use it to revert the merge without overwriting the public repo history. ;)

I also agree with you that currently testing GitHub Actions is not entirely optimized. Usually you can only test once they are already in production (I am thinking of actions triggered by events on master branch only, for example), which is not a good thing. It would be nice to think of an alternative procedure for testing actions outside the production...

And finally, when I asked in order to understand the pros/cons of each procedure, I was just trying to understand. I guessed there should be other additional reasons for rolling back, and I was just trying to find out those additional reasons for preferring current procedure. Thank you for your explanation. Now I understand better and yes, I agree those additional issues are not good for final users.

As I have told you, please let me work a little bit on the fork and see if the issues you mention can be fixed somehow. I would like to try. And it would be great to iterate with you to have your opinion and feed back to know whether it is worth or not.

Thank you again. And have a nice Sunday.

**Comment by hamelsmu** [comment]
Thanks Albert look forward to it

**Pull request merged**
