### PR TITLE
[Please Review] Search Highlighting

### PR DESCRIPTION
**Pull request by hamelsmu**
### Summary of changes

- removed.lunr.js
- added custom js suggested in https://github.com/fastai/fastpages/issues/111#issuecomment-591771232

### Before Change

image

### After Change

image

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 @xnutsive please review the new search functionality ( with keyword highlighting ), available for preview at this url: https://5e5cc653147b02444f44e1c9--fastpages.netlify.com/search/

🙇 Thank you

**Comment by jph00** [comment]
I don't feel like I have enough knowledge of this to give useful feedback. Is this JS still lunr, but just copied in? Or a fork of it? Or something else? How do we keep it updated as browsers change, security issues come up, etc? Sorry if these are dumb questions!

**Comment by hamelsmu** [comment]
@jph00 This is copied in from another repo, which is perhaps a little risky, as I wouldn't know  how to maintain it, and doesn't appear to be using a framework like lunr.js.  Also keep in mind that I am a javascript noob, and only know the basics at the moment, so even for the lunr.js approach, I copied that, too albiet that appears to be following a more standard path. 

I did find the flavor of search in this PR more useful as I can actually "see" the results of what I'm searching for, fwiw.  So what I'm saying is I'm asking for advice on what you folks think should be done here, because there are pros and cons.

**Comment by hamelsmu** [comment]
I suppose after thinking about it after being asked these questions, Im leaning towards closing this PR and not merging as it seems a bit risky to use something I completely don't understand?  

Perhaps it would better to build the same thing on top of lunr.js after doing more research and learning enough to be confident in maintaining it.  Something like how this site works: 
 https://pmarsceill.github.io/just-the-docs/docs/search/

**Comment by hamelsmu** [comment]
closing this for now feel free to disagree or whatever and I will reopen this PR thank you for asking questions etc.

**Comment by hamelsmu** [comment]
I'm working on this right now with lunr.js.  

I'm confident I'll be able to make this work with that framework.  I'll open a new PR this week

**Pull request closed without merging**
