### PR TITLE
Demonstration of CI Tool For fastpages

### PR DESCRIPTION
**Pull request by hamelsmu**
When receiving PRs from the community it can be cumbersome to validate PRs, as you have to pull down the new branch, build and serve the site locally and inspect it for changes.  

This is why I have created an Actions workflow that is triggered by the magic word `/preview` in a PR Comment, which will build the code on the PR and serve you a live preview.

### CODE REVIEW

**Comment by hamelsmu** [comment]
Okay here it goes!  

/preview

**Comment by hamelsmu** [comment]
@jph00 see the PR comments by the bot above.  let me know if this useful or any thoughts on the interface.

_P.S. I took a break from working on the blog to setup some better CI tools to help develop and maintain the blog_

**Comment by jph00** [comment]
Wow what an awesome idea! :) I love it.

**Comment by hamelsmu** [comment]
LOL weren't supposed to merge it, was a demo 😆  No big deal just funny

image

**Comment by jph00** [comment]
Ah I always merge PRs unless the title says not to - haven't seen a PR that hides "don't merge" inside the content like that ;)

I'll know to be on the lookout in the future...

**Pull request merged**
