### PR TITLE
escape liquid in code cells

### PR DESCRIPTION
**Pull request by hamelsmu**
This closes https://github.com/fastai/fastpages/issues/66

### CODE REVIEW

**Comment by hamelsmu** [comment]
@drscotthawley this takes care of the general problem of liquid syntax `{{` , `{%`, etc either being in your code or output of your code.  

We can scope your issue now to a feature request of "Plot.ly support"

**Comment by drscotthawley** [comment]
@hamelsmu  I'm still getting [non-escaped behavior](https://github.com/drscotthawley/devblog2/runs/454300277?check_suite_focus=true).  Do I need to pull from your fork upstream to mine?
If so, I tried following the [Merging an upstream branch into your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork) instructions, put when I got to step 4 ('git pull...'), I got... not conflicts, but rather...

```
shawley:~/devblog2$ git pull https://github.com/fastai/fastpages.git master
warning: no common commits
remote: Enumerating objects: 996, done.
remote: Total 996 (delta 0), reused 0 (delta 0), pack-reused 996
Receiving objects: 100% (996/996), 672.53 KiB | 4.98 MiB/s, done.
Resolving deltas: 100% (540/540), done.
From https://github.com/fastai/fastpages
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

**Comment by drscotthawley** [comment]
Wait, I got it!  Well I never got the upstream merge to work but I just grabbed your hide.tpl file, and...

Everything compiles and for the first time in...many attempts, my whole site builds!   :100: 

One question though: why does every markdown heading end with a paragraph symbol? 
https://drscotthawley.github.io/devblog2/2019/12/21/PCA-From-Scratch.html

**Pull request merged**
