### PR TITLE
added dos2unix conversion

### LINKED ISSUE #271: Microsoft Windows - CRLF to LF errors
When users running Microsoft Windows are running Docker for Windows they are encountering CRLF line ending problems causing Docker to complain.  **Does anyone know how to fix this issue permanently for windows users?**

An example of the errors encountered by these folks:

```
docker-compose down || true;
Removing fastpages_converter_1 ... done
Removing fastpages_fastpages_1 ... done
Removing fastpages_watcher_1   ... done
Removing fastpages_jekyll_1    ... done
Removing fastpages_jupyter_1   ... done
Removing network fastpages_default
docker-compose up
Creating network "fastpages_default" with the default driver
Creating fastpages_jekyll_1    ... done
Creating fastpages_watcher_1   ... done
Creating fastpages_jupyter_1   ... done
Creating fastpages_converter_1 ... done
Creating fastpages_fastpages_1 ... done
Attaching to fastpages_converter_1, fastpages_jupyter_1, fastpages_watcher_1, fastpages_fastpages_1, fastpages_jekyll_1
converter_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
fastpages_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
```

### Workarounds so far:

1. Replace offensive line endings with `sed`

If using WSL

```
sed -i 's/\r//g' /fastpages/action_entrypoint.sh
sed -i 's/\r//g' /fastpages/word2post.sh
```

if not using WSL

Download this file https://github.com/mbuilov/sed-windows/blob/master/sed-4.8-x64.exe

Run these commands 
```
sed -i "s/\r//g" _action_files/action_entrypoint.sh
sed -i "s/\r//g" _action_files/word2post.sh
```

2. Use `dos2unix`

Some articles shared by @noklam that might be helpful

- https://unix.stackexchange.com/questions/108588/shebang-line-not-working-with-cr-lf
- https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/

I have tried using this https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings in this repo, however, it doesn't seem to mitigate this issue.  Not sure what to do about this.

Related threads: 
- https://github.com/fastai/fastpages/issues/213
- https://github.com/fastai/fastpages/pull/145

### PR DESCRIPTION
**Pull request by hamelsmu**
closes #271 

This should fix the windows issue with the shell script permanently.  Thanks for sharing the article @noklam I only looked at it closely now and realized that the article contained the solution to this problem that has been plaguing users 🎉 

cc: @noklam @jvanelteren @ScottBrenner @Herman-Wu

### CODE REVIEW

**Comment by jvanelteren** [comment]
Thanks for looking into that. The automatic upgrade worked like a charm!! 

However I'm not there yet on Windows, after make build and make server I now get:
```
fastpages_1  | Agent pid 7
fastpages_1  | /fastpages/action_entrypoint.sh: /fastpages/word2post.sh: /bin/sh^M: bad interpreter: No such file or directory
converter_1  | Agent pid 7
converter_1  | /fastpages/action_entrypoint.sh: /fastpages/word2post.sh: /bin/sh^M: bad interpreter: No such file or directory
blog_fastpages_1 exited with code 126
blog_converter_1 exited with code 126 
```

**Comment by hamelsmu** [comment]
@jvanelteren can you try upgrading again?  I think I fixed the issue, now... let me know!

**Comment by ScottBrenner** [comment]
I've just pulled in the latest upgrade, did a `make remove` + `make build` + `make server`, and am now seeing this error:
```
$ make server
...
(repo)_jekyll_1 exited with code 1
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | chown: .jekyll-cache/Jekyll/Cache/Jekyll--Cache: Protocol error
jekyll_1     | chown: .jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown: Protocol error
(repo)_jekyll_1 exited with code 1
```

**Comment by jvanelteren** [comment]
For me, after upgrading, make build and make server, it seems to go ok, but when opening browser it doesn't show the blog (ERR_CONNECTION_REFUSED)
 
`$ "C:\Program Files (x86)\GnuWin32\bin\make.exe" server
docker-compose down --remove-orphans || true;
Removing blog_fastpages_1 ... done                                                                                      Removing blog_watcher_1   ... done                                                                                      Removing blog_jekyll_1    ... done                                                                                      Removing blog_converter_1 ... done                                                                                      Removing network blog_default
docker-compose up
Creating network "blog_default" with the default driver
Creating blog_watcher_1   ... done                                                                                      Creating blog_converter_1 ... done                                                                                      Creating blog_fastpages_1 ... done                                                                                      Creating blog_jekyll_1    ... done                                                                                      Attaching to blog_converter_1, blog_fastpages_1, blog_watcher_1, blog_jekyll_1
converter_1  | Agent pid 7
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | Agent pid 7
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
converter_1  | converting: _notebooks/2020-03-23-analyse.ipynb
fastpages_1  | converting: _notebooks/2020-03-23-analyse.ipynb
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
converter_1  | converting: _notebooks/2020-04-22-flights_above_nl.ipynb
fastpages_1  | converting: _notebooks/2020-04-22-flights_above_nl.ipynb
jekyll_1     | ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating...
jekyll_1     |       Remote Theme: Using theme jekyll/minima
blog_converter_1 exited with code 0
blog_fastpages_1 exited with code 0
jekyll_1     |        Jekyll Feed: Generating feed for posts
jekyll_1     |                     done in 6.499 seconds.
jekyll_1     |  Auto-regeneration: enabled for '/data'
jekyll_1     |     Server address: http://0.0.0.0:4000/blog/`

**Comment by hamelsmu** [comment]
ERR connection refused makes me think your Docker instance isn't exposing your ports, or you have two Docker containers running and the other one is blocking 

Not sure though b/c I cannot reproduce

**Comment by hamelsmu** [comment]
@ScottBrenner what is your operating system?

**Comment by ScottBrenner** [comment]
Windows 10 Home. 

@jvanelteren You? The error goes away when closing/reopening my text editor (VS Code) but comes back after a bit .. I load the blog through http://192.168.99.100, the IP of my `docker-machine` (`docker-machine ip default`).

**Comment by jvanelteren** [comment]
@ScottBrenner YES thanks Scott, I also had to use docker toolbox and therefore use the same IP address and now I can confirm the blog loads. To me the ip address was not obvious.

Now the only thing is that the watcher is not rebuilding whenever I change a blog in the notebooks directory. Made a change, saved ipynb file and refreshed browser couple of times. When I restart the server it does display the new version. Should I make a separate issue for that @hamelsmu?

**Comment by ScottBrenner** [comment]
FWIW you can just run the "converter" image/container to refresh/rebuild things, no need to restart the entire server. Learned this because the watcher isn't working for me either 😇

**Comment by hamelsmu** [comment]
Can you folks try upgrading fastpages again, I just made some fixes that might fix this issue to the Docker container

Thanks let me know!

**Comment by hamelsmu** [comment]
@jvanelteren  if you are still having issues after upgrading, please yes open a separate issue so I can track it thank you

**Comment by jvanelteren** [comment]
After upgrading the blog loads, but no automatic changes: created #274

**Pull request merged**
