### PR TITLE
Add support for launching notebooks in Deepnote

### PR DESCRIPTION
**Pull request by jakubzitny**
## New Feature: Deepnote Badge
- Deepnote badge appears by default for notebooks along with GitHub, Colab and Binder badges
- Option to switch it off is similar to all other badges
- Details about the usage are added to README

## Preview
Screen Shot 2021-08-20 at 22 00 19

This PR is inspired by #216, feel free to correct me if I missed something.

Example notebook in Deepnote: https://deepnote.com/project/fastpages-QBBzHgACTRe9w3frw8LAzw/%2F_notebooks%2F2020-02-21-introducing-fastpages.ipynb

Disclaimer: I am a developer at [Deepnote](https://deepnote.com/), I am pushing this since some of our users requested this after migrating from Colab to Deepnote 🙂

### CODE REVIEW

**Comment by jakubzitny** [comment]
Any feedback or help with approving me as a first-time contributor, please @hamelsmu?

**Review by Dstiers1191 — APPROVED** [review]

**Comment by goodboychan** [comment]
Awesome! Can I apply it in my custom environment?

**Comment by jakubzitny** [comment]
@goodboychan you mean Deepnote Custom Environment? Not currently, I'm sorry. This just picks up the `.ipynb` on the fastpages / github, and creates a new project with it. We're working on a possibility to use your Dockerfile in GH repo to build the custom env, but it'll take some time since it's not a priority. For now, I just suggest adding a hidden cell to the notebook that installs all required stuff. Or prepare your custom environment project in Deepnote and link that directly in your blogpost or page. Anyone who duplicates your existing Deepnote project with custom env will get that custom env automatically (cached).


@Dstiers1191 / @hamelsmu  would it be possible to allow CI in this PR so we can see that everything is passing?

**Comment by goodboychan** [comment]
@jakubzitny No, I mean that I can test it on my fastpages.
See the application like [this](https://goodboychan.github.io/python/coursera/tensorflow_probability/icl/2021/09/14/03-Variational-AutoEncoder-Celeb-A.html)

Sorry for confusion.

**Comment by jakubzitny** [comment]
Oh, sorry about that @goodboychan. I think you'd have to merge the upstream version of fastpages, or somehow rebase to it. Once this is merged of course. Not sure what was your process of creating your own instance, but I'd guess rebase will work.

**Comment by jakubzitny** [comment]
@Dstiers1191 / @hamelsmu thanks for the approval. Is there anything on our side that we can do to help get this merged?

**Comment by hamelsmu** [comment]
I'll look into this today or tommorow sorry for the delay

**Comment by hamelsmu** [comment]
LGTM thanks for the update!

**Pull request merged**
