### PR TITLE
Add ability to add annotations and highlighting to blog posts

### PR DESCRIPTION
**Pull request by hamelsmu**
See: https://web.hypothes.is/

I learned about this [from folks in the Jupyter community](https://github.com/executablebooks/jupyter-book/issues/861).  It offers a way to highlight and annotate pages.  I propose adding this feature to fastpages but having it off by default.  (I can be convinced otherwise).

Link to a [demo page here](https://hamelsmu.github.io/hypothesis/jupyter/2020/02/20/test.html) where you can highlight some text and see. 

cc: @muellerzr @jph00

### CODE REVIEW

**Comment by tmabraham** [comment]
This is very interesting that you plan to add Hypothesis to fastpages. It is a fairly decent tool that has been useful for me to write notes and highlight different articles, blogposts, and more. My only qualm is that they don't have much user support (I requested a feature, and the issue was closed claiming that it was the same as a previous issue but it was not) and there hasn't been many new features to the tool. Even now, there still isn't an official way of easily exporting your annotations (see [this issue](https://github.com/hypothesis/product-backlog/issues/566)). Nevertheless, I still use Hypothesis on a somewhat regular basis.

I want to clarify what is the purpose you envision for having Hypothesis on fastpages. Are you proposing to have public annotations or you just want to encourage people to use Hypothesis?

I was looking into alternatives but most alternative tools are meant for readers and don't provide much abilities for a publisher to encourage annotations like you plan to do with fastpages... the only other tool that could do this was [this open-source tool](https://github.com/linkeddata/dokieli). So i will definitely give the Hypothesis team kudos for making it easy to embed a Hypothesis client in a webpage.

BTW I assume you have seen this discussion? (I found from your quote-retweet just recently):
https://github.com/executablebooks/jupyter-book/issues/861

Also, I added a public annotation as an example of how Hypothesis can be used. Here's a [shareable link](https://hyp.is/q7R5wtnFEeqG41fRYs4NAw/hamelsmu.github.io/hypothesis/jupyter/2020/02/20/test.html).

**Comment by hamelsmu** [comment]
Thanks for the background, @tmabraham !

> just want to encourage people to use Hypothesis?

I don't want to encourage anything, I just want to make it easier for people to read blog posts, highlight bits they find are useful, make notes in the margin, and share it if they like.  Is hypothes.is good for that purpose?  Are there any drawbacks to this?

**Comment by hamelsmu** [comment]
I’m going to open this PR so anyone can comment if they want

**Comment by hamelsmu** [comment]
I'm going to go ahead and merge this and see how it goes.

**Pull request merged**
