### PR TITLE
use better fonts [Discuss before Merging]

### PR DESCRIPTION
**Pull request by hamelsmu**
per https://github.com/fastai/fastpages/pull/21#discussion_r378556080

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 can you take a look at the preview link and see what you think?  To me, I'm not sure if the fonts seem right, but then again I may have some kind of weird taste.

**Comment by T-Holland** [comment]
Definitely an improvement @hamelsmu

**Comment by jph00** [comment]
Oh sorry I meant to only use code fonts for the code. Definitely not for the body text. You should use a font designed for ease and clarify of on-screen reading. I'm not familiar with Mac fonts, but for Windows probably best is to follow Microsoft's approach for their docs, which is: "Segoe UI,SegoeUI,Segoe WP,Helvetica Neue,Helvetica,Tahoma,Arial,sans-serif;"
image

For Mac just go with something that's commonly available and similar in style.

**Comment by hamelsmu** [comment]
ok I'm going to close this PR and start fresh

**Pull request closed without merging**
